version: '3'
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_HOST=${DB_ROOT_HOST}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    ports:
      - '3306:3306'
    volumes:
      - ./db/conf:/etc/mysql/conf.d/:ro
      - mysql_data:/var/lib/mysql
      - ./db/logs:/var/log/mysql

  api:
    image: node
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ./api:/app
    working_dir: /app
    command: npm run dev

volumes:
  mysql_data: